
INSERT INTO Fakulteler(Isim,Dekan)
values('ziraat fakultesi','Oktay Çalýþkan')
INSERT INTO Fakulteler(Isim,Dekan)
values('mühendislik fakultesi','zýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('Güzel Sanatlar Fakültesi','mýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('elektrik mühendisliði','kýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('mühendislik fakultesi','pýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('fen fakultesi','týrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('spor bilimleri fakultesi','cýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('mimarlýk ve tasarým fakultesi','gýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('mühendislik fakultesi','zýrtafoz adam')
INSERT INTO Fakulteler(Isim,Dekan)
values('havacýlýk ve uzay bilimleri fakultesi','býrtafoz adam')

INSERT INTO Bolumler(Isim,Fakulte_ID)
VALUES ('Fizik Bölümü',1)
INSERT INTO Bolumler(Isim,Fakulte_ID)
VALUES ('kimya Bölümü',1)
INSERT INTO Bolumler(Isim,Fakulte_ID)
VALUES ('Karþýlaþtýrmalý edebiyat',1)
INSERT INTO Bolumler(Isim,Fakulte_ID)
VALUES ('biyoloji bölümü',1)
INSERT INTO Bolumler(Isim,Fakulte_ID)
VALUES ('elektrik mühendisliði ',3)



