//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityfrmwrkKullanimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string summary { get; set; }
        public Nullable<double> ImdbScore { get; set; }
        public Nullable<double> Score { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> activity { get; set; }
    }
}
